#!/usr/bin/env bash
set -euo pipefail
SRC="$(cd "$(dirname "$0")" && pwd)"

BIN_DIR="${HOME}/.local/bin"
AGENTS_ROOT="${HOME}/.gemini/config/agents"
AGY_AGENT_DIR="${AGENTS_ROOT}/agy-orchestrator"
AGY_WORKER_DIR="${AGENTS_ROOT}/agy-worker"
AGY_SKILL_DIR="${HOME}/.gemini/config/skills/model-router"
CFG_DIR="${HOME}/.config/agy-orchestrator"
MARKER="agy-orchestrator:generated"

mkdir -p "$BIN_DIR" "$AGY_AGENT_DIR" "$AGY_WORKER_DIR" "$AGY_SKILL_DIR" "$CFG_DIR"
install -m 0755 "$SRC/bin/agy-exec" "$BIN_DIR/agy-exec"
install -m 0755 "$SRC/bin/agy-audit" "$BIN_DIR/agy-audit"
install -m 0644 "$SRC/agy/agents/agy-orchestrator/agent.md" "$AGY_AGENT_DIR/agent.md"
install -m 0644 "$SRC/agy/agents/agy-worker/agent.md" "$AGY_WORKER_DIR/agent.md"
install -m 0644 "$SRC/agy/skills/model-router/SKILL.md" "$AGY_SKILL_DIR/SKILL.md"

# One worker agent per route. The Agy bottom statusline renders the subagent's TypeName,
# so a per-route agent is what makes it read "Agent(sonnet)" instead of "Agent(agy-worker)".
# These names are ordinary words, so never clobber an agent this installer did not write.
render_worker() {
  local route="$1"
  local label="$2"
  local dot="$3"
  local dir="${AGENTS_ROOT}/${route}"
  local dest="${dir}/agent.md"
  if [[ -f "$dest" ]] && ! grep -q "$MARKER" "$dest"; then
    echo "  ! skipped '${route}': ${dest} exists and was not generated by this installer" >&2
    return 0
  fi
  mkdir -p "$dir"
  sed -e "s/__NAME__/${route}/g" -e "s/__ROUTE__/${route}/g" -e "s/__MODEL_LABEL__/${label}/g" -e "s/__DOT__/${dot}/g" \
    "$SRC/agy/templates/worker.md" > "$dest"
  chmod 0644 "$dest"
  echo "  + ${dest}"
}

echo "Rendering per-route worker agents:"
# Claude labels carry no version number: the route already names the model, and a stale
# version in the label is worse than none. The dot makes each worker's statusline row
# tell itself apart from its siblings at a glance.
render_worker haiku  "Claude Haiku" 🟢
render_worker sonnet "Claude Sonnet" 🔵
render_worker opus   "Claude Opus" 🟣
render_worker luna   "GPT-5.6 Luna" 🟡
render_worker terra  "GPT-5.6 Terra" 🟠
render_worker sol    "GPT-5.6 Sol" 🔴
if [[ ! -f "$CFG_DIR/models.env" ]]; then
  install -m 0600 "$SRC/config/models.env" "$CFG_DIR/models.env"
else
  echo "Keeping existing $CFG_DIR/models.env"
fi

cat <<MSG
Installed Agy Orchestrator.

Files:
  $BIN_DIR/agy-exec
  $BIN_DIR/agy-audit
  $AGY_AGENT_DIR/agent.md
  $AGY_WORKER_DIR/agent.md
  $AGENTS_ROOT/{haiku,sonnet,opus,luna,terra,sol}/agent.md
  $AGY_SKILL_DIR/SKILL.md
  $CFG_DIR/models.env

Next:
  1. Ensure ~/.local/bin is in PATH.
  2. Ensure 'claude' and 'codex' CLIs are installed and authenticated.
  3. Run: agy-exec --help
  4. Restart Agy/Antigravity CLI and open /agents.
  5. Select 'agy-orchestrator'.

Model IDs can be changed later in:
  $CFG_DIR/models.env
MSG
